config/routes.rb
Rails3JqueryAutocompleteApp::Application.routes.draw do
  get "welcome/show"
  get 'welcome/autocomplete_brand_name'
  get 'welcome/id_element_example'

  resources :products

  root :to => "welcome#show"
end

app/models/brand.rb
class Brand
  include Mongoid::Document
  field :name
end

app/models/brand_subtype.rb
class BrandSubtype < Brand
end

app/models/product.rb
class Product
  include Mongoid::Document
  field :brand_name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  autocomplete :brand, :name

  def show
    @product = Product.new
  end

  def id_element_example
    @product = Product.new
  end

  def ajax_form_example

  end

  def show_the_form
    @product = Product.new
  end

  def formtastic
    @product = Product.new
  end

  autocomplete :brand_subtype, :name
  def subtype
    @product = Product.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options! 
    options[:header_message] ||= "Invalid Fields"
    options[:message] ||= "Correct the following errors and try again."
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end
  
  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { page_title.to_s }
    @show_title = show_title
  end
  
  def show_title?
    @show_title
  end
  
  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end
  
  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) || "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= javascript_include_tag 'jquery-1.4.2.min.js', 'jquery-ui-1.8.2.custom.min.js', 'rails.js', 'autocomplete-rails.js' %>
    <%= stylesheet_link_tag 'jquery-ui-1.8.2.custom.css' %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/welcome/_form.html.erb
<%= form_for @product do |f| %>
  <%=f.label :brand_name %>
  <%=f.autocomplete_field :brand_name, welcome_autocomplete_brand_name_path, :id_element => "#id_element_placeholder" %>
  <%= label_tag :id_element_placeholder, 'Put the id here:' %>
  <%= text_field_tag :id_element_placeholder, '' %>
<% end %>

app/views/welcome/ajax_form_example.html.erb
<h1>Ajax Form Example</h1>
<%= link_to "Show the form", welcome_show_the_form_path, :remote => true %>
<div id="form_placeholder" ></div>

app/views/welcome/formtastic.html.erb
<h1>Welcome!</h1>
<%= semantic_form_for @product do |f| %>
  <%=f.label :brand_name %>
  <%=f.autocomplete_field :brand_name, welcome_autocomplete_brand_name_path, :id_element => "#id_element_placeholder" %>
  <%= label_tag :id_element_placeholder, 'Put the id here:' %>
  <%= text_field_tag :id_element_placeholder, '' %>
<% end %>
<%= link_to 'ID Element option example', welcome_id_element_example_path %>

app/views/welcome/id_element_example.html.erb
<h1>Welcome!</h1>
<%= render :partial => 'form' %>

app/views/welcome/show.html.erb
<h1>Welcome!</h1>
<%= form_for @product do |f| %>
  <%=f.label :brand_name %>
  <%=f.autocomplete_field :brand_name, welcome_autocomplete_brand_name_path %>
<% end %>
<%= link_to 'ID Element option example', welcome_id_element_example_path %>

app/views/welcome/show_the_form.js.erb
$('#form_placeholder').html('<%=escape_javascript(render(:partial => 'form'))%>');

app/views/welcome/subtype.html.erb
<h1>Welcome!</h1>
<%= form_for @product do |f| %>
  <%=f.label :brand_name %>
  <%=f.autocomplete_field :brand_name, welcome_autocomplete_brand_subtype_name_path %>
<% end %>